# Generated by Django 3.2.5 on 2022-01-06 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timewatchstore', '0002_subcategory_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='gender',
        ),
    ]
