# Generated by Django 3.2.5 on 2022-01-06 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timewatchstore', '0003_remove_subcategory_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender_category',
            field=models.ManyToManyField(blank=True, to='timewatchstore.GenderCategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timewatchstore.subcategory'),
        ),
    ]
